name: mapped
repository: https://github.com/blaugold/mapped
packages:
  - packages/**

command:
  version:
    linkToCommits: true
    branch: main

scripts:
  formatting:dart: dart format .

  formatting:dart:check: dart format --set-exit-if-changed --output none .

  analyze:
    run: melos exec -c 1 -- dart analyze --fatal-infos

  test:dart:
    run: melos exec -c 1 -- dart test -r expanded
    select-package:
      flutter: false
      dir-exists: test

  benchmarks:
    run: melos exec -c 1 -- flutter test -j 1 -r expanded
    select-package:
      scope: benchmarks
