name: benchmarks
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  mapped:
    path: ../mapped
  vector_tile: ^0.3.1

dev_dependencies:
  benchmark_harness: ^2.0.0
  flutter_test:
    sdk: flutter
